sudo: false # Enable container-based infrastructure

language: c
jdk:
    - oraclejdk8
# cache: apt # Enable caching on APT when it is available for our repo

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

branches:
    only:
        - master
        - dev-master

env:
    - CCNL_HOME="/home/travis/build/cn-uofbasel/ccn-lite" PATH=$PATH:"$CCNL_HOME/bin"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CCNL_HOME="/Users/travis/build/cn-uofbasel/ccn-lite"; export PATH=$PATH:"$CCNL_HOME/bin" ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openssl ; fi

addons:
    apt:
        packages:
            - libssl-dev
            - build-essential
#            - linux-headers-$(uname -r)

script:
    # Run build-test.sh
    # Ideally, build-test should be run without specifying the targets.
    # However, bt-lnxkernel, bt-demo-cisco2015, bt-nfn-ccnx2015, bt-nfn-cisco2015 removed because they fail
    - cd $CCNL_HOME/src
    - make clean
    - ./build-test.sh VERBOSE=1 echo-cores bt-relay bt-all bt-pkt bt-omnet bt-demo-ccnb bt-demo-ccnx2015 bt-demo-iot2014 bt-demo-ndn2013 bt-nfn-ccnb bt-nfn-iot2014 bt-nfn-ndn2013
